### ISSUE TITLE
Fails on big file (2.42GB)

### ISSUE THREAD

**Issue by rolfen** [roryrjb/sha1-file#1]
It fails when trying to open a MOV file that is 2.5GB in size.
```
RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at tryCreateBuffer (fs.js:475:21)
    at Object.fs.readFileSync (fs.js:520:14)
    at module.exports (C:\Users\R\code\backblaze-b2-dedupe\node_modules\sha1-file\index.js:24:19)
    at processFile (C:\Users\R\code\backblaze-b2-dedupe\localChecksums.js:19:13)
    at files.forEach (C:\Users\R\code\backblaze-b2-dedupe\localChecksums.js:54:5)
```
Fails when calling
```
class FastBuffer extends Uint8Array {
  constructor(arg1, arg2, arg3) {
    super(arg1, arg2, arg3);
  }
}
```
With (reported by debugger):
```
arg1:2604948189
arg2:undefined
arg3:undefined
this:undefined
```

The file size is 2.42 GB (2,604,948,189 bytes).
Node version 6.10.3 on Windows 7 64bit.

**Comment by roryrjb** [comment]
@rolfen apologies for the massive delay. I've just tried on a file just over 7 GB in size (7,128,580,628 bytes) and it succeeded. This was on Linux however and it's possible there is some random edge case here somewhere. Are you able to share a more complete code snippet?

**Comment by rolfen** [comment]
Hello,

Now I have done some work on this particular code again, and had the opportunity to test it:

```
SHA1 failed: ../../Downloads/IE11 - Win7 2.ova
RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:247:3)
    at tryCreateBuffer (fs.js:530:21)
    at Object.fs.readFileSync (fs.js:570:14)
    at module.exports (/Users/rolf/code/backblaze-b2-dedupe/node_modules/sha1-file/index.js:24:19)
    at processFile (/Users/rolf/code/backblaze-b2-dedupe/localChecksums.js:18:16)
    at files.forEach (/Users/rolf/code/backblaze-b2-dedupe/localChecksums.js:61:5)
    at Array.forEach (<anonymous>)
    at recursiveReaddir (/Users/rolf/code/backblaze-b2-dedupe/localChecksums.js:55:9)
    at /Users/rolf/code/backblaze-b2-dedupe/node_modules/recursive-readdir/index.js:81:22
    at /Users/rolf/code/backblaze-b2-dedupe/node_modules/recursive-readdir/index.js:81:22
```

I think it's because I'm using it synchronously, which in turn makes `sha1-file` use `readFileSync()` which has a 2GB buffer limit. I have to rewrite my code to be asynchronous and call `sha1-file` with a callback.

**Comment by roryrjb** [comment]
I've clarified this in the README. For anyone coming across this issue:

---

When using the _sync_ version (excluding the callback), you will be limited to a filesize of 2GB (1GB on 32-bit platforms), this is due to a *V8* restriction, see [this issue] https://github.com/nodejs/node/issues/1719) for more details.

---

@rolfen thanks again for pointing this out :+1:.

**Comment by rolfen** [comment]
@roryrjb thanks for having a look and sorry for taking up your time.
